### ISSUE TITLE
SessionStorage for the login tokens

### ISSUE THREAD

**Issue by Moschn** [amiv-eth/amiv-jsclient#2]
Currently the session tokens are stored in localStorage. There is also a SessionStorage that is possibly better suited for these tokens. 

[stackoverflow discussion](https://stackoverflow.com/questions/5523140/html5-local-storage-vs-session-storage)
> localStorage and sessionStorage both extend Storage. There is no difference between them except for the intended "non-persistence" of sessionStorage. That is, the data stored in localStorage persists until explicitly deleted. Changes made are saved and available for all current and future visits to the site. For sessionStorage, changes are only available per window (or tab in browsers like Chrome and Firefox). Changes made are saved and available for the current page, as well as future visits to the site on the same window. Once the window is closed, the storage is deleted.

**Comment by NotSpecial** [comment]
Mhh, do I understand correctly? 

If I close my browser, then `sessionStorage` is deleted? So everytime I open the browser I would have to log in again? 

Because in this case `localStorage` might be better after all

**Comment by Moschn** [comment]
I agree.

 I did not even read my own issue to the end. I just saw that there is a SessionStorage and thought this would be better suited. My bad

**Comment by fubu** [comment]
I think there is a use case for sessionStorage and delete-after-browser-close: public computers. Or in other words, I think the library should have a way to be told which storage to use, e.g. based on some "remember me" checkbox from the login page.
